In [3]:
import pandas as panda
import numpy as numpy
import math
import random

In [4]:
trainingData = panda.read_excel("Project3.xlsx", sheet_name="Training")
PredictData = panda.read_excel("Project3.xlsx", sheet_name="Predict")


In [5]:
def GetWlin(X,Y):
    XTX = numpy.dot(X.T, X)
    XTXIXT = numpy.dot(numpy.linalg.inv(XTX), X.T)

    return numpy.dot(XTXIXT, Y)

<b>1.a</b>

In [56]:
x0 = numpy.ones(numpy.size(trainingData["Midterm"]))
x1 = numpy.array(trainingData["Midterm"])
x2 = numpy.array(trainingData["Homework"])
x3 = numpy.array(trainingData["Quiz"])
Y = numpy.matrix(trainingData["Course Grade"]).T

X = numpy.matrix([x0, x1, x2, x3])
X = X.T

Wlin = GetWlin(X,Y)
print(Wlin)

file = open('1a.txt', 'w') 
print(Wlin, file = file) 
file.close() 

[[7.66712306]
 [0.31262773]
 [0.15289359]
 [0.43866389]]


<b>1.b</b>

In [58]:
p0 = numpy.ones(numpy.size(PredictData["Midterm"]))
p1 = numpy.array(PredictData["Midterm"])
p2 = numpy.array(PredictData["Homework"])
p3 = numpy.array(PredictData["Quiz"])

P = numpy.matrix([p0, p1, p2, p3]).T

PredictedY = numpy.dot(P,Wlin)

print(PredictedY)

file = open('1b.txt', 'w') 
print(PredictedY, file = file) 
file.close() 

[[66.2096111 ]
 [48.56357988]
 [75.74333708]
 [64.71719403]
 [68.00762601]
 [76.33680974]
 [69.53807621]
 [78.88380021]
 [77.34208887]
 [75.73992604]
 [72.74934632]
 [84.25469179]
 [68.69585682]
 [74.83081547]
 [84.69436523]
 [79.43723912]
 [67.87184302]
 [83.24640249]
 [70.41188903]
 [76.36749754]
 [86.19785409]
 [82.99433017]
 [81.359375  ]
 [79.6447532 ]
 [87.12889672]
 [82.85511768]
 [88.89039282]
 [87.28863086]
 [89.4819503 ]
 [82.5962048 ]
 [85.53397531]
 [82.33729193]
 [78.70194466]
 [64.25882868]
 [83.56003976]
 [85.28190298]
 [90.57272706]
 [86.06005202]
 [83.20788306]
 [88.85176949]
 [82.7173156 ]
 [91.23168049]
 [89.63675907]
 [82.77103045]
 [90.10912094]
 [84.87794661]
 [93.48555533]
 [91.44512948]
 [89.12577387]
 [97.77301547]
 [95.45365987]
 [90.02955821]
 [94.57633209]
 [94.53629834]]


<b>2.a</b>

<b>Pass = 1 and Fail = -1</b>

In [8]:
newY = numpy.ones(numpy.size(Y))

for i in range(numpy.size(Y)):
    if Y[i] < 70.0:
        newY[i] = -1
    else:
        newY[i] = 1

print(newY)

[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1

<b>2.b</b>

In [23]:
def GetError(Wlin, X, Y):
    power = numpy.multiply(Y, numpy.dot(Wlin.T,X))
    expPower = math.exp(power)

    return numpy.multiply(-Y,X) / (1.0 + expPower)

In [40]:
def LogisticRegressionWithStochasticGD(Wlin, X, Y, step, maxIterations):
    w0 = Wlin
    w1 = Wlin

    tolleranceArray = numpy.ones(numpy.size(Wlin))
    tolleranceArray = numpy.dot(0.000000001, tolleranceArray)

    for i in range(maxIterations):

        index = random.randint(0, numpy.size(Y) - 1)

        w1 = w0 - step * GetError(Wlin, X[index].T, Y[index])

        if (abs(w1 - w0) < tolleranceArray).all():
            return w1
            pass

        w0 = w1
        pass
    
    return w1

In [59]:
step = 0.0000001

print("step :", step)
print()

Wlin2 = numpy.matrix(numpy.zeros(numpy.size(Wlin))).T
print("w0 used:")
print(Wlin2)

WlinRegressed = LogisticRegressionWithStochasticGD(Wlin2, X, newY, step, 100000)

print()
print("After logistic Regression:")
print(WlinRegressed)

file = open('2b.txt', 'w') 
print(WlinRegressed, file = file) 
file.close() 

step : 1e-07

w0 used:
[[0.]
 [0.]
 [0.]
 [0.]]

After logistic Regression:
[[0.0034468 ]
 [0.29619615]
 [0.3146673 ]
 [0.3097572 ]]


<b>2.c</b>

In [60]:
PredictedY = numpy.dot(P, WlinRegressed)

for i in range(numpy.size(PredictedY)):
    if PredictedY[i] < 70.0:
        PredictedY[i] = -1
    else:
        PredictedY[i] = 1

print(PredictedY)
file = open('2c.txt', 'w') 
print(PredictedY, file = file) 
file.close() 

[[-1.]
 [-1.]
 [ 1.]
 [-1.]
 [-1.]
 [ 1.]
 [-1.]
 [ 1.]
 [ 1.]
 [-1.]
 [-1.]
 [ 1.]
 [-1.]
 [-1.]
 [ 1.]
 [ 1.]
 [-1.]
 [ 1.]
 [-1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [-1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]]
